name: Linter and Typecheck
run-name: ${{ github.actor }} triggered this
on: [push]
jobs: 
  run-linter-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: corepack pnpm install
      - name: Run Eslint
        run: corepack pnpm lint
      - name: Run typecheck
        run: corepack pnpm tsc
      
